G1-MO_AppMvc.Net/Areas/Seller/Controllers/HomeController.cs
using App.Data;
using App.Model;
using App.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace App.Areas.Seller.Controllers
{
	[Area("Seller")]
	[Authorize(Roles = RoleName.Seller)]

	public class HomeController : Controller
	{
		private readonly E_CommerceContext _context;
		private readonly UserManager<AppUser> _userManager;
		private readonly SignInManager<AppUser> _signInManager;

		public HomeController(E_CommerceContext context, UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
		{
			_context = context;
			_userManager = userManager;
			_signInManager = signInManager;
		}


		[HttpGet("/seller/")]
		public IActionResult Index()
		{

			string userId = _userManager.GetUserId(User);
			return View();
		}


	}
}

G1-MO_AppMvc.Net/Controllers/HomeController.cs
using App.Data;
using App.Models;
using App.Model;
using App.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;

namespace App.Controllers
{
	[RedirectAdmin]
	public class HomeController : Controller
	{
		private string admin = GetMD5("0");
		private string seller = GetMD5("1");
		private string buyer = GetMD5("2");
		private readonly UserManager<AppUser> _userManager;
		private readonly RoleManager<IdentityRole> _roleManager;
		public readonly AppDbContext _dbContext;
		private readonly E_CommerceContext _context;



		private readonly ILogger<HomeController> _logger;
		E_CommerceContext objModel = new E_CommerceContext();

		public HomeController(UserManager<AppUser> userManager, RoleManager<IdentityRole> roleManager, AppDbContext dbContext, ILogger<HomeController> logger, E_CommerceContext context)
		{
			_userManager = userManager;
			_roleManager = roleManager;
			_dbContext = dbContext;
			_logger = logger;
			_context = context;
		}

		public async Task<IActionResult> SeedDataAsync()
		{
			var rolenames = typeof(RoleName).GetFields().ToList();
			foreach (var r in rolenames)
			{
				var rolename = (string)r.GetRawConstantValue();
				var rfound = await _roleManager.FindByNameAsync(rolename);
				if (rfound == null)
				{
					await _roleManager.CreateAsync(new IdentityRole(rolename));
				}
			}
			//admin , admin123, admin@example.com
			var useradmin = await _userManager.FindByEmailAsync("admin");
			if (useradmin == null)
			{
				useradmin = new AppUser()
				{
					UserName = "admin",
					Email = "admin@example.com",
					EmailConfirmed = true,
				};
				await _userManager.CreateAsync(useradmin, "admin123");
				await _userManager.AddToRoleAsync(useradmin, RoleName.Administrator);
			}
			

			return View("Index");
		}


		public IActionResult Index()
		{
            var IdAccLoggedIn = _userManager.GetUserId(User);
            //check cookies, lấy ra cookies để kiểm tra

            //Danh sách Category
            var lsCategory = _context.Categories
                .AsNoTracking()
                .OrderByDescending(x => x.NameCate)
                .ToList();
            ViewBag.lsCategory = lsCategory;

			//Danh sách tất cả sp bestsaler chưa join====================================================
			List<Product> lsProduct = new List<Product>();
			

			lsProduct = _context.Products
                                .AsNoTracking()
								.Include(p => p.ProductItems).Include(i => i.ImgPros)
								.Where(u => u.StatusPro == 1 && u.IdAcc != IdAccLoggedIn)
								.OrderByDescending(p => p.UpdateDate != null ? p.UpdateDate : p.CreateDate).Take(8).ToList();

			
			


			var query = from p in _context.Products
						join c in _context.Categories on p.IdCate equals c.IdCate
						join pI in _context.ProductItems on p.IdPro equals pI.IdPro
						select new
						{
							Product = p,
							ProductItem = pI,
							Category = c
						};
			//Lấy ra một object
			var result = query.FirstOrDefault(); // Get the first or default item
			if (result != null)
			{
                var product = new ProCateProItemViewModel
                {
                    products = result.Product,
                    productItems = result.ProductItem,
                    categories = result.Category
                };
                ViewBag.Product = product;

            }
			var voucher = _context.Vouchers.Where(x=>x.UsageStatus == 1 && x.DeleteStatus == false && x.StartDate <= DateTime.Now).ToList();
			ViewBag.Voucher = voucher;




            return View(lsProduct);
		}


		

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
		

		//create a string MD5
		public static string GetMD5(string str)
		{
			MD5 md5 = new MD5CryptoServiceProvider();
			byte[] fromData = Encoding.UTF8.GetBytes(str);
			byte[] targetData = md5.ComputeHash(fromData);
			string byte2String = null;

			for (int i = 0; i < targetData.Length; i++)
			{
				byte2String += targetData[i].ToString("x2");

			}
			return byte2String;
		}

	}
}

G1-MO_AppMvc.Net/Controllers/WishController.cs
using App.Model;
using App.Models;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace App.Controllers
{
    [Authorize]
    public class WishController : Controller
    {
        private readonly E_CommerceContext _context;
        public INotyfService _Inotiyfyservice { get; }
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;

        public WishController(E_CommerceContext context, INotyfService inotiyfyservice, UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            _context = context;
            _Inotiyfyservice = inotiyfyservice;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public string GenerateNextWishListId()
        {
            // Retrieve the maximum existing Id_pro
            string maxIdAcc = _context.Wishlists
                .Select(p => p.IdWishlist)
                .OrderByDescending(id => id)
                .FirstOrDefault();

            // Generate the next Id_pro
            int nextNumber = 1;
            if (!string.IsNullOrEmpty(maxIdAcc))
            {
                string numericPart = maxIdAcc.Substring(2); // Extract numeric part
                if (int.TryParse(numericPart, out int numericValue))
                {
                    nextNumber = numericValue + 1;
                }
            }

            string nextIdAcc = $"WL{nextNumber:D3}"; // Format the new Id_acc

            return nextIdAcc;
        }

        public IActionResult Index()
        {
            var userId = _userManager.GetUserId(User);
            var wishlist = _context.Wishlists.Include(p => p.IdProNavigation).ThenInclude(i => i.ImgPros).Include(pr => pr.IdProNavigation.ProductItems).Where(u => u.IdAcc == userId).ToList();
            return View(wishlist);
        }
        [HttpGet]
        public async Task<IActionResult> Create(string id, string url)
        {
            var userId = _userManager.GetUserId(User);
            var existingWishlistItem = await _context.Wishlists
     .FirstOrDefaultAsync(w => w.IdAcc == userId && w.IdPro == id);

            if (existingWishlistItem == null)
            {
                // Nếu sản phẩm chưa tồn tại trong Wishlist, thêm mới
                var wishlist = new Wishlist
                {
                    IdWishlist = GenerateNextWishListId(),
                    IdPro = id,
                    IdAcc = userId
                };

                await _context.Wishlists.AddAsync(wishlist);
                await _context.SaveChangesAsync();
                _Inotiyfyservice.Success("Add to wish list successfully!", 3);
            } else
            {
                _Inotiyfyservice.Warning("Product exist in your wish list!", 3);
            }
            return RedirectToAction("Index", url);
        }
        [HttpGet]
        public async Task<IActionResult> Remove(string id)
        {
            var wish = await _context.Wishlists.FindAsync(id);
            if (wish != null)
            {
                 _context.Wishlists.Remove(wish);
                await _context.SaveChangesAsync();
                _Inotiyfyservice.Success("Remove successfully", 2);
            }
            return RedirectToAction("Index");
        }
    }
}

G1-MO_AppMvc.Net/Views/Home/Index.cshtml
@model IEnumerable<App.Model.Product>
@{

    ViewData["Title"] = "Home Page";
    App.Model.ProCateProItemViewModel Product = ViewBag.Product;
    List<App.Model.Voucher> voucher = ViewBag.Voucher;
}
@section Style {
    <style>
        body {
            background-color: #eee
        }

        .card {
            border: none;
            position: relative
        }

        .off {
            font-size: 36px;
            margin-top: -16px !important;
            color: blue
        }

        .flat {
            font-size: 20px
        }

        .star {
            margin-top: 25px !important;
            font-size: 28px
        }

        .line {
            padding-right: 8rem !important;
            padding-left: 8rem !important
        }

            .line hr {
                height: 2px
            }
    </style>
}
<section class="hero">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <partial name="_CatePartial" />
            </div>
            <div class="col-lg-9">
                <partial name="_SearchPartial" />
                <partial name="_BannerPartial" />

            </div>
        </div>
    </div>
</section>
<!-- Hero Section End -->
<div class="section-title mt-5">
    <h2>Coupon</h2>
</div>
<!-- Categories Section Begin -->
<section class="categories">
    <div class="container">
        <div class="row">
            <div class="categories__slider owl-carousel owl-loaded owl-drag">
                <div class="owl-stage-outer">
                    <div class="owl-stage" style="transform: translate3d(-1170px, 0px, 0px); transition: all 1.2s ease 0s; width: 3803px;">
                        @foreach (var item in voucher)
                        {
                            <div class="owl-item cloned" style="width: 292.5px;">
                                <div class="card">

                                    <div class="text-center"> <small class="text-uppercase flat">@item.PromotionName</small> </div>
                                    <div class="d-flex justify-content-center px-2">
                                        <div class="d-flex flex-row">
                                            @if (@item.DiscountType == 1)
                                            {
                                                <h5 class="mt-0 off">@item.DiscountAmount %</h5> <sup class="mt-2 text-primary star">*</sup>
                                            }
                                            else
                                            {
                                                <h5 class="mt-0 off">@item.DiscountAmount đ</h5> <sup class="mt-2 text-primary star">*</sup>
                                            }
                                           
                                        </div>
                                    </div>
                                    <div class="line">
                                        <hr>
                                    </div>
                                    <div class="text-center mb-5"> <span class="text-uppercase">@item.PromotionCode</span> </div>
                                    <div class="text-right p-1"> <small>Valid till @item.EndDate</small> </div>
                                </div>
                            </div>
                        }

                    </div>
                </div><div class="owl-nav"><button type="button" role="presentation" class="owl-prev"><span class="fa fa-angle-left"><span></span></span></button><button type="button" role="presentation" class="owl-next"><span class="fa fa-angle-right"><span></span></span></button></div><div class="owl-dots disabled"></div>
            </div>
        </div>
    </div>
</section>
<!-- Categories Section End -->
<!-- Featured Section Begin -->
<div class="section-title mt-5">
    <h2>News Product</h2>
</div>
<section class="featured spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
            </div>
        </div>

        <div class="row featured__filter">

            @if (Model != null && Model.Count() > 0)
            {
                foreach (var product in Model)
                {
                    string linkimg = "";

                    string url = $"/{product.Name}-{product.IdPro}";
                    <div class="col-lg-3 col-md-4 col-sm-6 mix oranges fresh-meat">
                        <div class="featured__item">
                            @foreach (var img in product.ImgPros)
                            {
                                linkimg = img.LinkImg;
                                break;
                            }
                            <div class="featured__item__pic set-bg" data-setbg="/assests/img/product/@linkimg">
                                <ul class="featured__item__pic__hover">
                                    <li><a asp-action="Create" asp-controller="Wish" asp-route-url="Home" asp-route-id="@product.IdPro"><i class="fa fa-heart"></i></a></li>


                                </ul>
                            </div>
                            <div class="featured__item__text">
                                <h6><a href="@url">@product.Name</a></h6>
                                @if (product.ProductItems.Count() > 1 && product.ProductItems != null)
                                {
                                    var max = product.ProductItems.Max(u => u.ProPrice);
                                    var min = product.ProductItems.Min(u => u.ProPrice);
                                    <h5>@min ~ @max VND</h5>
                                }
                                else
                                {
                                    var max = product.ProductItems.Max(u => u.ProPrice);
                                    <h5>@max VND</h5>
                                }
                            </div>
                        </div>
                    </div>


                }
            }
            else
            {
                <div class="container d-flex justify-content-center">
                    <img src="~/assests/img/surprise.png" style="width: 50%" />
                </div>
            }

        </div>
    </div>


</section>